### ISSUE TITLE
Setup a unit testing suite to run as Github Actions

### ISSUE THREAD

**Issue by johnsBeharry** [peakshift/telegram-dogecoin#27]
```yaml
Due: 2021-02-14
Reward: 100 Doge
Expiration: 2021-02-14
```

We need to start doing automated testing.
